### ISSUE TITLE
Syllabus Adjustment

### ISSUE THREAD

**Issue by cmadland** [cmadland/edci338-202201#123]
Hello everyone...

This issue will be a discussion of a proposal to drop the second Showcase Post and distribute the value of that post (15%) to the first showcase post, the major project, and the celebration of learning post, so the new grading scheme would be:

| Item | Old Value | New Value|
|---|---|---|
|Showcase post 1 | 15% | 20%|
|Showcase Post 2 | 15%| Not Required |
| Major Project | 40% | 45%|
Celebration of Learning | 30% | 35% |

If you have any concerns about this, please either leave a comment below, or send me an email if you would prefer to not share your situation. I'm more than happy to work with you.

I think this will ease your workload towards the end of the semester and still allow me to assess your attainment of the learning outcomes.

Let me know what you think below.

**Comment by pipercote** [comment]
I'm for it!

**Comment by alirezat137886** [comment]
Sounds good to me!

**Comment by EDCI338** [comment]
Sounds good:)

**Comment by tiannaroutley** [comment]
I completely agree! I think it will definitely ease the amount of work placed in the second half of this course. One point of concern I do have is that I'm unsure where my grade sits in this course, so I worry if we increase the percent worth how it would affect my current grade. I'm thoroughly invested and enjoying this form of evaluation, but maybe we could receive a current letter grade to know an approximate range at which we currently stand:)

**Comment by cmadland** [comment]
Good question Tianna...you should have received a level on the SOLO taxonomy in your feedback on the showcase post (if not, I'll get that to you asap). The levels on the [SOLO Taxonomy](https://teaching.madland.ca/solo) can be mapped to UVic letter grades.

Also, I don't 'average' your scores to come to a grade, so a lower grade early in the course can be completely erased by consistent higher grades later, which doesn't happen with averaged scores.

I'm happy to meet with you individually to chat about where you are at. I believe that assessment should be a conversation.

**Comment by tiannaroutley** [comment]
Thanks for getting back to me! That definitely brought clarity to my worries. I haven't yet received feedback, but I have assigned you to my tracking and EDCI issue! This approach is definitely something very unfamiliar to me, but that's super awesome to hear that a negative "grade", in the beginning, wouldn't weigh down your course mark. I will schedule a meeting to converse about my showcase post and current standing in the course. Thanks again for the clarification:)

**Comment by shaafijahangir** [comment]
Sounds good to me too!

**Comment by miaharmitage** [comment]
Perhaps in order to be evaluated on more than three assignments, maybe we could submit three Wow and Wonder posts (each worth 5%) in order to make up for the showcase post percentage? However, if this seems like something which would be too much marking to have completed near the end of the semester I completely understand that and in that case, I am good with moving the weight of the second showcase post to the other three assignments!

**Comment by cmadland** [comment]
Hi @miaharmitage, I think there will be enough for me to go on with three formal assessments. That said, though, if you feel that I've missed something in my assessment of your work, I'm happy to look at further evidence such as Wows and Wonders.

**Comment by cmadland** [comment]
I'm going to consider this decided as I haven't heard any objections.
